---
name: Label auto-merge PRs

on:
  pull_request_target:
    types: [auto_merge_enabled, auto_merge_disabled]

env:
  LABEL_NAME: 'automerge :bell:'

permissions:
  contents: read

jobs:
  add-remove-label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142  # tag=v2.7.0
        with:
          egress-policy: audit

      - name: Update label
        run: |
          if [[ "${{ github.event.action }}" == "auto_merge_enabled" ]]; then
            gh pr edit ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --add-label "${{ env.LABEL_NAME }}"
          elif [[ "${{ github.event.action }}" == "auto_merge_disabled" ]]; then
            gh pr edit ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --remove-label "${{ env.LABEL_NAME }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
